name: Build

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'Main-0.14.1'

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build --stacktrace --info

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-artifact
          path: build/libs/*.jar
          retention-days: 7
